
[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https:; connect-src 'self' https:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-ancestors 'none';"

[[redirects]]
  from = "/api/iban_issue_token"
  to = "/.netlify/functions/iban_issue_token"
  status = 200

[[redirects]]
  from = "/api/iban_check"
  to = "/.netlify/functions/iban_check"
  status = 200

[[redirects]]
  from = "/api/iban_submit"
  to = "/.netlify/functions/iban_submit"
  status = 200
